global using Avalonia.Controls;
global using Avalonia;
global using Avalonia.Data.Converters;
global using System.Windows.Input;
global using Avalonia.Interactivity;
global using Avalonia.Input;
global using Avalonia.Controls.Metadata;
global using Avalonia.Controls.Shapes;
global using Avalonia.Controls.Documents;
global using Avalonia.Data;
global using Avalonia.Layout;
global using Avalonia.Media;
global using Nodify.Compatibility;
global using System.Linq;
global using Avalonia.Styling;
global using Avalonia.Controls.Primitives;
global using Avalonia.Controls.Presenters;
global using Avalonia.Controls.Selection;
global using Avalonia.Markup.Xaml.Templates;
global using Avalonia.Metadata;
global using Avalonia.Threading;
global using Avalonia.Controls.Templates;
global using Avalonia.VisualTree;
global using Avalonia.Animation;
global using Avalonia.Controls.Mixins;
global using Avalonia.Collections;
global using System.Runtime.CompilerServices;
global using System.Collections.Generic;
global using System.Threading;

global using FrameworkElement = Avalonia.Controls.Control;
global using DependencyObject = Avalonia.AvaloniaObject;
global using UIElement = Avalonia.Controls.Control;
global using DependencyPropertyChangedEventArgs = Avalonia.AvaloniaPropertyChangedEventArgs;
global using SizeChangedInfo = Avalonia.Controls.SizeChangedEventArgs;
global using System;
global using Avalonia.Interactivity;
global using RoutedEventHandler = System.EventHandler<Avalonia.Interactivity.RoutedEventArgs>;
global using ModifierKeys = Avalonia.Input.KeyModifiers;
global using UIElementCollection = Avalonia.Controls.Controls;