global using Avalonia.Controls;
global using Avalonia;
global using Avalonia.Data.Converters;
global using Avalonia.Markup.Xaml;
global using System.Windows.Input;
global using Avalonia.Interactivity;
global using Avalonia.Controls.ApplicationLifetimes;
global using Avalonia.Input;
global using Avalonia.LogicalTree;
global using Avalonia.Threading;
global using Nodify.Compatibility;
global using Avalonia.Media;
global using System;
global using MouseEventArgs = Avalonia.Input.PointerEventArgs;